def menu2():
    print("\33[1;31;40m")
    print("╔═════════════════════╗")
    print("║  Oyunlar            ║")   
    print("║  1-Tetris           ║")
    print("║  2-Adam asmaca      ║")
    print("║  3-Yilan            ║")
    print("║                     ║")
    print("║  5-Çikis yapin      ║")
    print("║    Seçim yapin      ║") 
    print("╚═════════════════════╝")

    secim=input("Seçiminizi yapiniz : ")  
    if secim == "1" : print("Tetris Seçildi")
    if secim == "2" : print("Adam asmaca seçildi")
    if secim == "3" : print("Yilan Seçildi")