def aramenu():
    print("\33[1;31;40m")
    print("╔═════════════════════╗")
    print("║  Hesap Makinesi     ║")   
    print("║  1-Toplama          ║")
    print("║  2-Çikarma          ║")
    print("║  3-Bölme            ║")
    print("║  4-Çarpma           ║")
    print("║  5-Çikis yapin      ║")
    print("║    Seçim yapin      ║") 
    print("╚═════════════════════╝")
    secim=input("Seçiminizi yapiniz : ")  
    if secim == "1" : print("Toplama seçildi")
    if secim == "2" : print("Çikarma seçildi")    
    if secim == "3" : print("Bölme seçildi")   
    if secim == "4" : print("Çarpma seçildi")  
    if secim == "5" : print("Çikis yapildi")    
    if secim in ["1","2","3","4","5"]: pass
    else: print("Yanlis secim yaptiniz")
    toplama = input("toplamak istediğiniz sayıları giriniz:")
    if toplama in ["1","2","3","4","5","6","7","8","9","0"]: pass